cryptotracker/back_testing/urls.py
from django.urls import path
from . import views

app_name = 'back_testing'
urlpatterns = [
    path('strategies/', views.StrategyView.as_view(), name="strategies")
]

cryptotracker/cryptotracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    #path('', include('home.urls')),
    path('', include('tracker.urls')),
    path('backtesting/', include('back_testing.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
]

cryptotracker/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.index, name='index'),
]

cryptotracker/tracker/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'tracker'
urlpatterns = [
    #path('', views.SymbolListView.as_view(), name='all'),
    #path('symbol/<int:pk>/', views.SymbolDetailView.as_view(), name='symbol_detail'),
    path('', views.Chart.as_view(), name="all"),
]

cryptotracker/services/models.py
from django.db import models

# Create your models here.

cryptotracker/tracker/models.py
from django.db import models

# Create your models here.

class Symbol(models.Model):
    symbol = models.CharField(max_length=10)

    def __str__(self):
        return self.symbol

class PriceData(models.Model):
    symbol = models.ForeignKey(Symbol, on_delete=models.CASCADE)
    date = models.DateTimeField()
    open = models.FloatField()
    high= models.FloatField() 
    low= models.FloatField()
    close= models.FloatField()

cryptotracker/back_testing/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

# Others
from services.scripts.backtesting_services import run_backtest
from services.scripts.backtesting_services import get_symbol_data

# Create your views here.
class StrategyView(LoginRequiredMixin, View):
    template_name = 'back_testing/strategies_view.html'
    context = {}

    def get_backtesting_data(self, symbol, interval, periods): 
        df = get_symbol_data(symbol, interval)
        df = run_backtest(symbol, periods, df)
        return df

    def get(self, request):
        
        if request.GET:
            symbol = request.GET.get('symbol')
            interval = request.GET.get('interval')
            strategy = request.GET.get('strategy')

            if "100" in strategy:
                periods = [50, 100]
            else:
                periods = [20, 50]

            result = self.get_backtesting_data(symbol, interval, periods)
            self.context = {
                "symbol": symbol,
                "interval": interval,
                "strategy": strategy,
                "result": round(result.iloc[0]['ret'], 2),
            }

        return render(request, self.template_name, self.context)

cryptotracker/home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context = {}
    return render(request, 'home/index.html', context)

cryptotracker/services/views.py
from django.shortcuts import render

# Create your views here.

cryptotracker/tracker/views.py
# Django Stuffs
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from django.http import JsonResponse
from django.http import HttpResponse
from django.urls import reverse

# Others
from json import dumps
from datetime import date, datetime
from services.scripts.backtesting_services import get_symbol_data
import matplotlib.pyplot as plt
import io
import urllib
import base64
import time

# Models
from tracker.models import Symbol, PriceData

# Create your views here.


class SymbolListView(ListView):
    model = Symbol


class SymbolDetailView(LoginRequiredMixin, DetailView):
    model = Symbol
    #template_name = "tracker/symbol_detail.html"


class Chart(View):
    template_name = 'tracker/chart.html'

    def json_serial(self, obj):
        """JSON serializer for objects not serializable by default json code"""

        if isinstance(obj, (datetime, date)):
            return obj.isoformat()
        raise TypeError("Type %s not serializable" % type(obj))

    # References
    # https://stackoverflow.com/questions/11875770/how-to-overcome-datetime-datetime-not-json-serializable

    def chart_data(self, symbol="BTCUSDT", interval="4H"):
        df = get_symbol_data(symbol, interval)
        return df

    def convert_df_to_list(self, df):
        price_data = df['Open'].tolist()
        price_date = df.index.tolist()

        return price_data, price_date

    def get(self, request):
        if request.GET:
            symbol = request.GET.get('symbol')
            interval = request.GET.get('interval')

            df = self.chart_data(symbol, interval)
            price_data, price_date = self.convert_df_to_list(df)

            return JsonResponse({
                'symbol': symbol,
                'price': price_data,
                'date': price_date
            })

        df = self.chart_data()
        price_data, price_date = self.convert_df_to_list(df)

        context = {'symbol': "BTCUSDT",
                   'price': price_data,
                   'date': price_date
                   }

        dataJSON = dumps(context, default=self.json_serial)

        return render(request, self.template_name, {'data': dataJSON})

'''
def plot_test(request):
    start = time.time()
    plt.plot(range(10))
    fig = plt.gcf()
    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    string = base64.b64encode(buf.read())
    uri = urllib.parse.quote(string)
    end = time.time()
    print("took", end - start)
    return render(request, 'tracker/plot_test.html', {'data': uri})'''

cryptotracker/back_testing/templates/back_testing/strategies_view.html
{% extends "base.html" %}

{% block content %}
    
    <!-- Select crypto -->
    <form method="GET">
        <select name="symbol" id="symbol">
            <option>BTCUSDT</option>
            <option>ETHUSDT</option>
            <option>ADAUSDT</option>
            <option>XRPUSDT</option>
        </select>

        <!-- Select interval -->
        <select name="interval" id="interval">
            <option>1D</option>
            <option>4H</option>
            <option>1H</option>
        </select>

        <!-- Select Strategy -->
        <select name="strategy" id="strategy">
            <option>SMACross(50, 100)</option>
            <option>SmaCrossShortTerm(20, 50)</option>
        </select>

        <input type="submit" name="submit" id="submit" value="Calculate">
    </form>

    {{symbol}}
    {{interval}}
    {{strategy}}
    {{result}}
    {{output}}

{% endblock %}

cryptotracker/home/templates/base.html
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
    <title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

    {% block head %} {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'tracker:all' %}">Chart</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'back_testing:strategies' %}"
                >Backtest</a
              >
            </li>
          </ul>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'login' %}"
                >Login</a
              >
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'logout' %}?next={% url 'tracker:all' %}"
                >Logout</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}{% endblock %}
  </body>
</html>

cryptotracker/home/templates/home/index.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'tracker:all' %}">tracker</a>
{% endblock %}

cryptotracker/tracker/templates/tracker/chart.html
{% extends "base.html" %}

{% block head %} 
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
{% endblock %}

{% block content %}

    
    <!-- Select crypto -->
    <select name="symbol" id="symbol">
        <option>BTCUSDT</option>
        <option>ETHUSDT</option>
        <option>ADAUSDT</option>
        <option>XRPUSDT</option>
    </select>

    <!-- Select interval -->
    <select name="interval" id="interval">
        <option>1D</option>
        <option>4H</option>
        <option>1H</option>
    </select>
    


    <div class="chart-content" style="width: 50vw; max-height: 30vh;">
        <canvas id="myChart" width="400" height="400"></canvas>
    </div>
    <script>
        $(document).ready(function () {
            var data = JSON.parse("{{data|escapejs}}");

            const ctx = document.getElementById('myChart').getContext('2d');
            const myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: data.date, //date would go here
                    datasets: [{
                        label: data.symbol,
                        data: data.price  //price would go here
                    }]
                },
                
            });
            $('#symbol, #interval').change(function (e) {
                $.ajax({
                    url: '',
                    type: 'GET',
                    data: {
                        symbol: $('#symbol').val(),
                        interval: $('#interval').val()
                    },
                    success: function (response) {
                        myChart.data.datasets[0].label = response.symbol;
                        myChart.data.labels = response.date;
                        myChart.data.datasets[0].data = response.price;
                        myChart.update()
                    }
                })
                e.preventDefault();
            })
        })
    </script>
    {% load static %}
    <!--<script src="{% static 'tracker/js/chart.js' %}"></script> -->
{% endblock %}

cryptotracker/tracker/templates/tracker/form_view.html
<form method="GET">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
<p>{{ form.symbol_choice.value }} da</p>

cryptotracker/tracker/templates/tracker/plot_test.html
{% extends "base.html" %}

{% block content %}
    
    <img src="data:img/png;base64, {{ data }}" height="250" width="250">

{% endblock %}

cryptotracker/tracker/templates/tracker/symbol_detail.html
{% extends "base.html" %}

{% block content %}

<h1>{{ symbol.symbol }}</h1>
<a href="{% url 'tracker:all' %}"> All symbols </a>

{% endblock %}

cryptotracker/tracker/templates/tracker/symbol_list.html
{% extends "base.html" %}

{% block content %}
    {% if symbol_list %}
        {% for symbol in symbol_list%}
            <li>
                <a href="{% url 'tracker:symbol_detail' symbol.id %}"> {{symbol.symbol}} </a>
        {% endfor %}
            </li>
    {% endif %}
    </p>
    <a href="{% url 'login' %}?next={{ request.path }}">Login</a>

    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}?next={% url 'tracker:all' %}">Logout</a>
    {% endif %}
    
    <a href="{% url 'tracker:chart' %}">Chart</a>
{% endblock %}